version: "3"

services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4443:4443"
      - "4442:4442"
      - "4444:4444"
    shm_size: '1gb'
    depends_on:
      - scrapper

  scrapper:
    build:
      context: .
    volumes:
      - /api
    ports:
      - "5000:5000"


  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - scrapper
      ports:
        - "6127:6127"

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A crawl.celery worker -l info
    # command:  ['celery', '-A', 'app.tasks', 'worker']
    links:
      - redis
    depends_on:
      - redis
      - scrapper   